# Generated by Django 4.0.4 on 2022-06-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='short_text',
            field=models.CharField(default='short text', max_length=100, verbose_name='Короткий опис'),
            preserve_default=False,
        ),
    ]
