# Generated by Django 4.0.4 on 2022-06-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_short_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='author', max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(default='2022', max_length=4, verbose_name='Рік видання'),
        ),
        migrations.AlterField(
            model_name='book',
            name='short_text',
            field=models.CharField(default='short text', max_length=100, verbose_name='Короткий опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(default='Long text', verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='title', max_length=50, verbose_name='Назва'),
        ),
    ]
